version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x ./install-terraform.sh 
      - chmod +x ./configure-named-profile.sh 
      - chmod +x ./apply-terraform.sh # make files executable
      - ls -la
      - cd cicd
      #- echo Running install-terraform.sh...
      - ./install-terraform.sh # install terraform
      #- ./configure-named-profile.sh
      #- cd cicd # change directory
      #- ./cicd/configure-named-profile.sh # configure named profile

  build:
    commands:
      #- echo build phase...
     # - configure-named-profile.sh
      - ./apply-terraform.sh
