version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
     # - cd cicd # change directory
     # - chmod +x ./install-terraform.sh configure-named-profile.sh apply-terraform.sh # make files executable
     # - ls -la
     # - ./install-terraform.sh # install terraform
     # - ./configure-named-profile.sh # configure named profile

      - chmod +x ./install-terraform.sh
      - chmod +x ./configure-named-profile.sh
      - chmod +x ./apply-terraform.sh
      - echo Running install-terraform.sh...
      - ./install-terraform.sh

  build:
    commands:
      - ./apply-terraform.sh
